services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    volumes:
      - ./config:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=arch-services.mywire.org
    networks:
      - proxy-net
      - socket-net
    labels:
      - "traefik.enable=true"
      # Public (HTTPS)
      - "traefik.http.routers.homepage.rule=Host(`arch-services.mywire.org`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"

      # Public (Redirect)      - "traefik.http.routers.homepage-red.rule=Host(`arch-services.mywire.org`)"
      - "traefik.http.routers.homepage-red.entrypoints=web"
      - "traefik.http.routers.homepage-red.middlewares=https-redirect@docker"

      # Local (HTTP)
      - "traefik.http.routers.homepage-local.rule=Host(`homepage.localhost`) || Host(`dashboard.localhost`) || Host(`localhost`)"


      - "traefik.http.routers.homepage-local.entrypoints=web"
      
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"


networks:
  proxy-net:
    external: true
  socket-net:
    external: true

