services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    environment:
      - REACT_APP_BACKEND_V2_GET_URL=https://excalidraw.arch-services.mywire.org/api/v2
      - REACT_APP_BACKEND_V2_POST_URL=https://excalidraw.arch-services.mywire.org/api/v2
      - REACT_APP_WS_SERVER_URL=wss://excalidraw.arch-services.mywire.org/socket.io
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.arch-services.mywire.org`)"
      - "traefik.http.routers.excalidraw.entrypoints=websecure"
      - "traefik.http.routers.excalidraw.tls=true"
      - "traefik.http.routers.excalidraw.tls.certresolver=myresolver"
      - "traefik.http.routers.excalidraw-red.rule=Host(`excalidraw.arch-services.mywire.org`)"
      - "traefik.http.routers.excalidraw-red.entrypoints=web"
      - "traefik.http.routers.excalidraw-red.middlewares=https-redirect@docker"
      - "traefik.http.routers.excalidraw-local.rule=Host(`excalidraw.localhost`)"
      - "traefik.http.routers.excalidraw-local.entrypoints=web"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"

  excalidraw-room:
    image: excalidraw/excalidraw-room:latest
    restart: on-failure
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw-room.rule=Host(`excalidraw.arch-services.mywire.org`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.excalidraw-room.entrypoints=websecure"
      - "traefik.http.routers.excalidraw-room.tls=true"
      - "traefik.http.routers.excalidraw-room.tls.certresolver=myresolver"
      - "traefik.http.routers.excalidraw-room-red.rule=Host(`excalidraw.arch-services.mywire.org`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.excalidraw-room-red.entrypoints=web"
      - "traefik.http.routers.excalidraw-room-red.middlewares=https-redirect@docker"
      - "traefik.http.routers.excalidraw-room-local.rule=Host(`excalidraw.localhost`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.excalidraw-room-local.entrypoints=web"
      - "traefik.http.services.excalidraw-room.loadbalancer.server.port=8080"

networks:
  proxy-net:
    external: true
