services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_API_VERSION=1.40
    networks:
      - proxy-net
      - socket-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs.rule=Host(`logs.arch-services.mywire.org`) || Host(`logs.localhost`)"

      - "traefik.http.routers.logs.entrypoints=websecure"
      - "traefik.http.routers.logs.tls.certresolver=myresolver"
      - "traefik.http.routers.logs.middlewares=authelia-auth@docker"

networks:
  proxy-net:
    external: true
  socket-net:
    external: true
