services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - DOCKER_API_VERSION=1.40
    networks:
      - proxy-net
      - socket-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logs.rule=Host(`logs.arch-services.mywire.org`)"
      - "traefik.http.routers.logs.entrypoints=websecure"
      - "traefik.http.routers.logs.tls=true"
      - "traefik.http.routers.logs.middlewares=authelia-auth@docker"
      - "traefik.http.routers.logs-red.rule=Host(`logs.arch-services.mywire.org`)"
      - "traefik.http.routers.logs-red.entrypoints=web"
      - "traefik.http.routers.logs-red.middlewares=https-redirect@docker"
      - "traefik.http.routers.logs-local.rule=Host(`logs.localhost`)"
      - "traefik.http.routers.logs-local.entrypoints=web"

networks:
  proxy-net:
    external: true
  socket-net:
    external: true
