services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    command: serve
    environment:
      - TZ=UTC
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=tcp://socket-proxy:2375
      - DOCKER_API_VERSION=1.40
    volumes:
      - "./data:/data"
    networks:
      - socket-net

networks:
  socket-net:
    external: true
