services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ACCELERATE_SYSTEM=1
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ollama_data:/root/.ollama:rw
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.arch-services.mywire.org`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls.certresolver=myresolver"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"
      - "traefik.http.services.ollama.loadbalancer.healthcheck.path=/api/tags"
      - "traefik.http.services.ollama.loadbalancer.healthcheck.interval=10s"

volumes:
  ollama_data:

networks:
  proxy-net:
    external: true
