server:
  address: tcp://0.0.0.0:9091

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: "auth.arch-services.mywire.org"
      policy: bypass
    - domain: "*.arch-services.mywire.org"
      policy: one_factor

session:
  name: authelia_session
  secret: "{{ env \"AUTHELIA_SESSION_SECRET\" }}"
  expiration: 3600
  inactivity: 300
  remember_me: 1M
  cookies:
    - domain: arch-services.mywire.org
      authelia_url: https://auth.arch-services.mywire.org

identity_validation:
  reset_password:
    jwt_secret: "{{ env \"AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET\" }}"

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: "{{ env \"AUTHELIA_STORAGE_ENCRYPTION_KEY\" }}"

notifier:
  filesystem:
    filename: /config/emails.txt
