services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    command: -H tcp://socket-proxy:2375
    volumes:
      - portainer_data:/data
    networks:
      - socket-net
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.arch-services.mywire.org`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer-svc"
      - "traefik.http.routers.portainer-red.rule=Host(`portainer.arch-services.mywire.org`)"
      - "traefik.http.routers.portainer-red.entrypoints=web"
      - "traefik.http.routers.portainer-red.middlewares=https-redirect@docker"

      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"


networks:
  socket-net:
    external: true
  proxy-net:
    external: true

volumes:
  portainer_data:
