---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- My Projects:
    - Github:
        - abbr: GH
          href: https://github.com/kiskaadee?tab=repositories

- Social Media:
    - Instagram:
        - abbr: IN
          href: https://www.instagram.com/tierraenmisbotas//

- Learning Content:
    - YouTube:
        - abbr: YT
          href: https://www.youtube.com/@scicreep8979
