---
# Applications Group
- Applications:
    # - Gitea:
    #     icon: gitea.png
    #     href: https://gitea.arch-services.mywire.org
    #     description: Git Service
    #     server: my-docker
    #     container: gitea
    # - Ollama:
    #     icon: ollama.png
    #     href: https://ollama.arch-services.mywire.org
    #     description: AI Model Runner
    #     server: my-docker
    #     container: ollama-ollama-1
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.arch-services.mywire.org
        description: Media Server
        server: my-docker
        container: jellyfin
    - Excalidraw:
        icon: excalidraw.png
        href: https://excalidraw.arch-services.mywire.org
        description: Sketching Tool
        server: my-docker
        container: excalidraw-excalidraw-1
    - Mermaid:
        icon: mermaid.png
        href: https://mermaid.arch-services.mywire.org
        description: Diagramming Tool
        server: my-docker
        container: mermaid-live-editor
 
