services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: always
    volumes:
      - ./config:/config
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      # Public (HTTPS)
      - "traefik.http.routers.authelia.rule=Host(`auth.arch-services.mywire.org`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls=true"

      # Public (Redirect)
      - "traefik.http.routers.authelia-red.rule=Host(`auth.arch-services.mywire.org`)"
      - "traefik.http.routers.authelia-red.entrypoints=web"
      - "traefik.http.routers.authelia-red.middlewares=https-redirect@docker"

      # Local (HTTP)
      - "traefik.http.routers.authelia-local.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.authelia-local.entrypoints=web"


networks:
  proxy-net:
    external: true
