services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.arch-services.mywire.org`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.middlewares=authelia-auth@docker"
      - "traefik.http.routers.gitea-red.rule=Host(`gitea.arch-services.mywire.org`)"
      - "traefik.http.routers.gitea-red.entrypoints=web"
      - "traefik.http.routers.gitea-red.middlewares=https-redirect@docker"
      - "traefik.http.routers.gitea-local.rule=Host(`gitea.localhost`)"
      - "traefik.http.routers.gitea-local.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

networks:
  proxy-net:
    external: true
